plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.launch.game'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.launch.game"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "1.2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    flavorDimensions "load"
    productFlavors {
        light {
            dimension "load"
            applicationIdSuffix ".light"
            resValue "string", "app_name", "Game-Light"
            buildConfigField "int", "LOAD_DURATION_MS", "3000"
        }
        medium {
            dimension "load"
            applicationIdSuffix ".medium"
            resValue "string", "app_name", "Game-Medium"
            buildConfigField "int", "LOAD_DURATION_MS", "10000"
        }
        heavy {
            dimension "load"
            applicationIdSuffix ".heavy"
            resValue "string", "app_name", "Game-Heavy"
            buildConfigField "int", "LOAD_DURATION_MS", "20000"
        }
    }

    signingConfigs {
        release {
            storeFile file(System.getenv("KEYSTORE_FILE_PATH") ?: "$System.env.HOME/Code/APK-Key/Chris/keystore.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: "123456"
            keyAlias System.getenv("KEY_ALIAS") ?: "key0"
            keyPassword System.getenv("KEY_PASSWORD") ?: "123456"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // 添加 load-config 依赖
    implementation project(':load-config')
    implementation project(':launch-common')

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}