plugins {
    id 'convention.android-app'
}

android {
    namespace 'com.example.launch.game'

    defaultConfig {
        applicationId "com.example.launch.game"
        versionCode 3
        versionName "1.2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    flavorDimensions "load"
    productFlavors {
        light {
            dimension "load"
            applicationIdSuffix ".light"
            resValue "string", "app_name", "Game-Light"
            buildConfigField "int", "LOAD_DURATION_MS", "3000"
        }
        medium {
            dimension "load"
            applicationIdSuffix ".medium"
            resValue "string", "app_name", "Game-Medium"
            buildConfigField "int", "LOAD_DURATION_MS", "10000"
        }
        heavy {
            dimension "load"
            applicationIdSuffix ".heavy"
            resValue "string", "app_name", "Game-Heavy"
            buildConfigField "int", "LOAD_DURATION_MS", "20000"
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout

    implementation project(':load-config')
    implementation project(':launch-common')

    testImplementation libs.junit
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core
}
