plugins {
    id 'convention.android-library'
}

android {
    namespace 'com.example.loadconfig'

    defaultConfig {
        minSdk 21
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
}

dependencies {
    api libs.annotation
    api libs.lifecycle.common
    api libs.recyclerview
}
