plugins {
    id 'convention.android-app'
}

android {
    namespace 'com.example.wechatfriendforvideo'

    defaultConfig {
        applicationId "com.example.wechatfriendforvideo"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
}

dependencies {
    implementation project(':load-config')
    implementation project(':scrolling-common')
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.glide
    annotationProcessor libs.glide.compiler
    implementation libs.photoview
    implementation libs.viewpager2

    implementation libs.media3.exoplayer
    implementation libs.media3.ui
    implementation libs.media3.common

    testImplementation libs.junit
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core
}
