plugins {
    id 'convention.android-app'
}

android {
    namespace 'com.example.wechatfriendformixedrender'

    defaultConfig {
        applicationId "com.example.wechatfriendformixedrender"
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation project(':load-config')
    implementation project(':scrolling-common')
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.recyclerview
}
