plugins {
    id 'convention.android-app'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.launch.gl'

    defaultConfig {
        applicationId "com.example.launch.gl"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    flavorDimensions "load"
    productFlavors {
        light {
            dimension "load"
            applicationIdSuffix ".light"
            resValue "string", "app_name", "GL-Light"
        }
        medium {
            dimension "load"
            applicationIdSuffix ".medium"
            resValue "string", "app_name", "GL-Medium"
        }
        heavy {
            dimension "load"
            applicationIdSuffix ".heavy"
            resValue "string", "app_name", "GL-Heavy"
        }
    }
}

dependencies {
    implementation project(':launch-common')
    implementation libs.core.ktx
    implementation libs.appcompat
}
