plugins {
    id 'convention.android-app'
}

android {
    namespace 'com.example.wechatfriendforglmap'

    defaultConfig {
        applicationId "com.example.wechatfriendforglmap"
        versionCode 3
        versionName "1.2.0"
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation project(':load-config')
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
}
