pluginManagement {
    includeBuild("build-logic")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.mozilla.org/maven2/' }
    }
}

include ':app'
include ':load-config'
include ':scrolling-common'
include ':scrolling-aosp-power'
include ':scrolling-aosp-performance'
include ':scrolling-aosp-picasso'
include ':scrolling-webview'
include ':scrolling-aosp-customscroller'
include ':scrolling-aosp-renderstress'
include ':scrolling-aosp-softwarerender'
include ':scrolling-compose'
include ':scrolling-surface-map'
include ':scrolling-aosp-purerenderthread'
include ':scrolling-aosp-dualwindow'
include ':scrolling-aosp-mixedrender'
include ':scrolling-gl-map'
include ':scrolling-aosp-douyin'
include ':scrolling-aosp-video'
include ':scrolling-aosp-ebook'
include ':scrolling-webview-surface'
include ':scrolling-webview-texture'
include ':scrolling-webview-imagereader'
include ':launch-common'
include ':launch-aosp'
include ':launch-compose'
include ':launch-webview'
include ':launch-gl'
include ':launch-game'
include ':switch-common'
include ':switch-aosp'
include ':switch-webview'
include ':switch-flutter'
