include ':app'
include ':wechatfriendforpower'
include ':wechatfriendforperformance'
include ':wechatfriendforwebview'
include ':wechatfriendforcustomscroller'
include ':wechatfriendforrenderstress'
include ':wechatfriendforsoftwarerender'
include ':wechatfriendforcompose'
include ':wechatfriendforsurfacemap'
include ':wechatfriendforpurerenderthread'
include ':wechatfriendfordualwindow'
include ':wechatfriendformixedrender'
include ':wechatfriendforglmap'
