include ':app'
include ':load-config'
include ':scrolling-aosp-power'
include ':scrolling-aosp-performance'
include ':scrolling-aosp-picasso'
include ':scrolling-webview'
include ':scrolling-aosp-customscroller'
include ':scrolling-aosp-renderstress'
include ':scrolling-aosp-softwarerender'
include ':scrolling-compose'
include ':scrolling-surface-map'
include ':scrolling-aosp-purerenderthread'
include ':scrolling-aosp-dualwindow'
include ':scrolling-aosp-mixedrender'
include ':scrolling-gl-map'
include ':scrolling-aosp-douyin'
include ':scrolling-aosp-video'
include ':scrolling-aosp-ebook'
include ':scrolling-webview-surface'
include ':scrolling-webview-texture'
include ':scrolling-webview-imagereader'
include ':launch-common'
include ':launch-aosp'
include ':launch-compose'
include ':launch-webview'
include ':launch-gl'
include ':launch-game'
