plugins {
    id 'convention.android-app'
}

android {
    namespace 'com.example.wechatfriendfordualwindow'

    defaultConfig {
        applicationId "com.example.wechatfriendfordualwindow"
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation project(':load-config')
    implementation project(':scrolling-common')
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.recyclerview

    // Glide for image loading
    implementation libs.glide
    annotationProcessor libs.glide.compiler
}
