plugins {
    id 'convention.android-app'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.switch_aosp'

    defaultConfig {
        applicationId "com.example.switch_aosp"
        versionCode 3
        versionName "1.2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

dependencies {
    implementation project(':switch-common')
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.recyclerview
}
