plugins {
    id 'convention.android-library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.launch.common'

    defaultConfig {
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    flavorDimensions "load"
    productFlavors {
        light {
            dimension "load"
            buildConfigField "String", "LOAD_TYPE", "\"LIGHT\""
        }
        medium {
            dimension "load"
            buildConfigField "String", "LOAD_TYPE", "\"MEDIUM\""
        }
        heavy {
            dimension "load"
            buildConfigField "String", "LOAD_TYPE", "\"HEAVY\""
        }
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    api libs.coroutines.core
    api libs.coroutines.android
}
