plugins {
    id 'convention.android-app'
}

android {
    defaultConfig {
        applicationId "com.kcrason.highperformancefriendscircle"
        minSdk 21
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
    namespace 'com.kcrason.highperformancefriendscircle'
}

dependencies {
    implementation project(':load-config')
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.swiperefreshlayout
    testImplementation libs.junit
    androidTestImplementation libs.test.runner
    androidTestImplementation libs.espresso.core
    implementation libs.recyclerview
    implementation libs.glide
    annotationProcessor libs.glide.compiler
    implementation libs.rxandroid
    implementation libs.rxjava
    implementation libs.photoview
    implementation libs.viewpager2
}
