plugins {
    id 'convention.android-app'
    id 'org.jetbrains.kotlin.android'
    id 'convention.android-compose'
}

android {
    namespace 'com.example.launch.compose'

    defaultConfig {
        applicationId "com.example.launch.compose"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    flavorDimensions "load"
    productFlavors {
        light {
            dimension "load"
            applicationIdSuffix ".light"
            resValue "string", "app_name", "Comps-Light"
        }
        medium {
            dimension "load"
            applicationIdSuffix ".medium"
            resValue "string", "app_name", "Comps-Medium"
        }
        heavy {
            dimension "load"
            applicationIdSuffix ".heavy"
            resValue "string", "app_name", "Comps-Heavy"
        }
    }

    buildFeatures {
        compose true
    }
}

dependencies {
    implementation project(':launch-common')
    implementation libs.core.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.activity.compose
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.ui.graphics
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material3
    implementation libs.appcompat
}
