plugins {
    id 'convention.android-app'
}

android {
    namespace 'com.example.wechatfriendforsurfacemap'

    defaultConfig {
        applicationId "com.example.wechatfriendforsurfacemap"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation project(':load-config')
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core
}
