plugins {
    id 'convention.android-app'
}

android {
    namespace 'com.android.wechatfriendforpower'

    defaultConfig {
        applicationId "com.android.wechatfriendforpower"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation project(':load-config')
    implementation project(':scrolling-common')
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.recyclerview
    implementation libs.swiperefreshlayout
    implementation libs.glide
    implementation libs.material
    annotationProcessor libs.glide.compiler
    implementation libs.rxandroid
    implementation libs.rxjava
    implementation libs.photoview
    implementation libs.viewpager2

    testImplementation libs.junit
    testImplementation libs.mockito.core
    testImplementation libs.robolectric
    testImplementation libs.test.core
    testImplementation libs.test.ext.junit

    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core
}
