plugins {
    id 'convention.android-app'
    id 'org.jetbrains.kotlin.android'
    id 'convention.android-compose'
}

android {
    namespace 'com.example.wechatfriendforcompose'

    defaultConfig {
        applicationId "com.example.wechatfriendforcompose"
        versionCode 3
        versionName "1.2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildFeatures {
        compose true
    }

    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    implementation project(':load-config')
    implementation libs.core.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.activity.compose

    // Compose BOM
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.ui.graphics
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.material3
    implementation libs.compose.foundation

    // Navigation
    implementation libs.navigation.compose

    // Coil for image loading
    implementation libs.coil.compose

    // For tracing
    implementation libs.tracing.ktx

    testImplementation libs.junit
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation platform(libs.compose.bom)
    androidTestImplementation libs.compose.ui.test.junit4

    debugImplementation libs.compose.ui.tooling
    debugImplementation libs.compose.ui.test.manifest
}
