plugins {
    id 'convention.android-app'
}

android {
    namespace 'com.example.wechatfriendforwebview'

    defaultConfig {
        applicationId "com.example.wechatfriendforwebview"
        versionCode 3
        versionName "1.2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation project(':load-config')
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.recyclerview

    // WebView相关
    implementation libs.webkit

    // Glide图片加载
    implementation libs.glide

    // 导入RxJava
    implementation libs.rxjava
    implementation libs.rxandroid

    testImplementation libs.junit
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core
}
