plugins {
    id 'convention.android-app'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.launch.aosp'

    defaultConfig {
        applicationId "com.example.launch.aosp"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    flavorDimensions "load"
    productFlavors {
        light {
            dimension "load"
            applicationIdSuffix ".light"
            resValue "string", "app_name", "AOSP-Light"
        }
        medium {
            dimension "load"
            applicationIdSuffix ".medium"
            resValue "string", "app_name", "AOSP-Medium"
        }
        heavy {
            dimension "load"
            applicationIdSuffix ".heavy"
            resValue "string", "app_name", "AOSP-Heavy"
        }
    }
}

dependencies {
    implementation project(':launch-common')
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
}
