plugins {
    id 'convention.android-app'
}

android {
    namespace 'com.example.wechatfriendforebook'

    defaultConfig {
        applicationId "com.example.wechatfriendforebook"
        versionCode 3
        versionName "1.2.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation project(':scrolling-common')
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout

    implementation libs.lifecycle.livedata
    implementation libs.lifecycle.viewmodel
    implementation libs.lifecycle.runtime

    implementation libs.jsoup

    testImplementation libs.junit
    androidTestImplementation libs.test.ext.junit
    androidTestImplementation libs.espresso.core
}
